//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Domashki
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Домашка.
    /// </summary>
    // *** Start programmer edit section *** (Домашка CustomAttributes)

    // *** End programmer edit section *** (Домашка CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДомашкаE", new string[] {
            "Тема as \'Тема\'",
            "Дата as \'Дата\'",
            "Оценка as \'Оценка\'"})]
    public class Домашка : ICSSoft.STORMNET.DataObject
    {
        
        private string fТема;
        
        private System.DateTime fДата;
        
        private int fОценка;
        
        private IIS.Domashki.Журнал fЖурнал;
        
        // *** Start programmer edit section *** (Домашка CustomMembers)

        // *** End programmer edit section *** (Домашка CustomMembers)

        
        /// <summary>
        /// Тема.
        /// </summary>
        // *** Start programmer edit section *** (Домашка.Тема CustomAttributes)

        // *** End programmer edit section *** (Домашка.Тема CustomAttributes)
        [StrLen(255)]
        public virtual string Тема
        {
            get
            {
                // *** Start programmer edit section *** (Домашка.Тема Get start)

                // *** End programmer edit section *** (Домашка.Тема Get start)
                string result = this.fТема;
                // *** Start programmer edit section *** (Домашка.Тема Get end)

                // *** End programmer edit section *** (Домашка.Тема Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Домашка.Тема Set start)

                // *** End programmer edit section *** (Домашка.Тема Set start)
                this.fТема = value;
                // *** Start programmer edit section *** (Домашка.Тема Set end)

                // *** End programmer edit section *** (Домашка.Тема Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Домашка.Дата CustomAttributes)

        // *** End programmer edit section *** (Домашка.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Домашка.Дата Get start)

                // *** End programmer edit section *** (Домашка.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Домашка.Дата Get end)

                // *** End programmer edit section *** (Домашка.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Домашка.Дата Set start)

                // *** End programmer edit section *** (Домашка.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Домашка.Дата Set end)

                // *** End programmer edit section *** (Домашка.Дата Set end)
            }
        }
        
        /// <summary>
        /// Оценка.
        /// </summary>
        // *** Start programmer edit section *** (Домашка.Оценка CustomAttributes)

        // *** End programmer edit section *** (Домашка.Оценка CustomAttributes)
        public virtual int Оценка
        {
            get
            {
                // *** Start programmer edit section *** (Домашка.Оценка Get start)

                // *** End programmer edit section *** (Домашка.Оценка Get start)
                int result = this.fОценка;
                // *** Start programmer edit section *** (Домашка.Оценка Get end)

                // *** End programmer edit section *** (Домашка.Оценка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Домашка.Оценка Set start)

                // *** End programmer edit section *** (Домашка.Оценка Set start)
                this.fОценка = value;
                // *** Start programmer edit section *** (Домашка.Оценка Set end)

                // *** End programmer edit section *** (Домашка.Оценка Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Domashki.Журнал.
        /// </summary>
        // *** Start programmer edit section *** (Домашка.Журнал CustomAttributes)

        // *** End programmer edit section *** (Домашка.Журнал CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.Domashki.Журнал Журнал
        {
            get
            {
                // *** Start programmer edit section *** (Домашка.Журнал Get start)

                // *** End programmer edit section *** (Домашка.Журнал Get start)
                IIS.Domashki.Журнал result = this.fЖурнал;
                // *** Start programmer edit section *** (Домашка.Журнал Get end)

                // *** End programmer edit section *** (Домашка.Журнал Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Домашка.Журнал Set start)

                // *** End programmer edit section *** (Домашка.Журнал Set start)
                this.fЖурнал = value;
                // *** Start programmer edit section *** (Домашка.Журнал Set end)

                // *** End programmer edit section *** (Домашка.Журнал Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДомашкаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДомашкаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДомашкаE", typeof(IIS.Domashki.Домашка));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Домашка.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfДомашка CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfДомашка CustomAttributes)
    public class DetailArrayOfДомашка : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Domashki.DetailArrayOfДомашка members)

        // *** End programmer edit section *** (IIS.Domashki.DetailArrayOfДомашка members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Домашка by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Домашка.
        /// </summary>
        public DetailArrayOfДомашка(IIS.Domashki.Журнал fЖурнал) : 
                base(typeof(Домашка), ((ICSSoft.STORMNET.DataObject)(fЖурнал)))
        {
        }
        
        public IIS.Domashki.Домашка this[int index]
        {
            get
            {
                return ((IIS.Domashki.Домашка)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Domashki.Домашка dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
