//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Domashki
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Журнал.
    /// </summary>
    // *** Start programmer edit section *** (Журнал CustomAttributes)

    // *** End programmer edit section *** (Журнал CustomAttributes)
    [AutoAltered()]
    [Caption("Журнал оценок")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЖурналE", new string[] {
            "Курс as \'Курс\'",
            "Итог as \'Итог\'",
            "Дисциплина as \'Дисциплина\'",
            "Дисциплина.Название as \'Название\'"}, Hidden=new string[] {
            "Дисциплина.Название"})]
    [AssociatedDetailViewAttribute("ЖурналE", "Домашка", "ДомашкаE", true, "", "Домашка", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ЖурналE", "Дисциплина", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [View("ЖурналL", new string[] {
            "Курс as \'Курс\'",
            "Итог as \'Итог\'",
            "Дисциплина.Название as \'Название\'"})]
    public class Журнал : ICSSoft.STORMNET.DataObject
    {
        
        private int fКурс;
        
        private int fИтог;
        
        private IIS.Domashki.Дисциплина fДисциплина;
        
        private IIS.Domashki.DetailArrayOfДомашка fДомашка;
        
        // *** Start programmer edit section *** (Журнал CustomMembers)

        // *** End programmer edit section *** (Журнал CustomMembers)

        
        /// <summary>
        /// Курс.
        /// </summary>
        // *** Start programmer edit section *** (Журнал.Курс CustomAttributes)

        // *** End programmer edit section *** (Журнал.Курс CustomAttributes)
        public virtual int Курс
        {
            get
            {
                // *** Start programmer edit section *** (Журнал.Курс Get start)

                // *** End programmer edit section *** (Журнал.Курс Get start)
                int result = this.fКурс;
                // *** Start programmer edit section *** (Журнал.Курс Get end)

                // *** End programmer edit section *** (Журнал.Курс Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Журнал.Курс Set start)

                // *** End programmer edit section *** (Журнал.Курс Set start)
                this.fКурс = value;
                // *** Start programmer edit section *** (Журнал.Курс Set end)

                // *** End programmer edit section *** (Журнал.Курс Set end)
            }
        }
        
        /// <summary>
        /// Итог.
        /// </summary>
        // *** Start programmer edit section *** (Журнал.Итог CustomAttributes)

        // *** End programmer edit section *** (Журнал.Итог CustomAttributes)
        public virtual int Итог
        {
            get
            {
                // *** Start programmer edit section *** (Журнал.Итог Get start)

                // *** End programmer edit section *** (Журнал.Итог Get start)
                int result = this.fИтог;
                // *** Start programmer edit section *** (Журнал.Итог Get end)

                // *** End programmer edit section *** (Журнал.Итог Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Журнал.Итог Set start)

                // *** End programmer edit section *** (Журнал.Итог Set start)
                this.fИтог = value;
                // *** Start programmer edit section *** (Журнал.Итог Set end)

                // *** End programmer edit section *** (Журнал.Итог Set end)
            }
        }
        
        /// <summary>
        /// Журнал.
        /// </summary>
        // *** Start programmer edit section *** (Журнал.Дисциплина CustomAttributes)

        // *** End programmer edit section *** (Журнал.Дисциплина CustomAttributes)
        [NotNull()]
        public virtual IIS.Domashki.Дисциплина Дисциплина
        {
            get
            {
                // *** Start programmer edit section *** (Журнал.Дисциплина Get start)

                // *** End programmer edit section *** (Журнал.Дисциплина Get start)
                IIS.Domashki.Дисциплина result = this.fДисциплина;
                // *** Start programmer edit section *** (Журнал.Дисциплина Get end)

                // *** End programmer edit section *** (Журнал.Дисциплина Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Журнал.Дисциплина Set start)

                // *** End programmer edit section *** (Журнал.Дисциплина Set start)
                this.fДисциплина = value;
                // *** Start programmer edit section *** (Журнал.Дисциплина Set end)

                // *** End programmer edit section *** (Журнал.Дисциплина Set end)
            }
        }
        
        /// <summary>
        /// Журнал.
        /// </summary>
        // *** Start programmer edit section *** (Журнал.Домашка CustomAttributes)

        // *** End programmer edit section *** (Журнал.Домашка CustomAttributes)
        public virtual IIS.Domashki.DetailArrayOfДомашка Домашка
        {
            get
            {
                // *** Start programmer edit section *** (Журнал.Домашка Get start)

                // *** End programmer edit section *** (Журнал.Домашка Get start)
                if ((this.fДомашка == null))
                {
                    this.fДомашка = new IIS.Domashki.DetailArrayOfДомашка(this);
                }
                IIS.Domashki.DetailArrayOfДомашка result = this.fДомашка;
                // *** Start programmer edit section *** (Журнал.Домашка Get end)

                // *** End programmer edit section *** (Журнал.Домашка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Журнал.Домашка Set start)

                // *** End programmer edit section *** (Журнал.Домашка Set start)
                this.fДомашка = value;
                // *** Start programmer edit section *** (Журнал.Домашка Set end)

                // *** End programmer edit section *** (Журнал.Домашка Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЖурналE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЖурналE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЖурналE", typeof(IIS.Domashki.Журнал));
                }
            }
            
            /// <summary>
            /// "ЖурналL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЖурналL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЖурналL", typeof(IIS.Domashki.Журнал));
                }
            }
        }
    }
}
